/*-
 * #%L
 * Chat Assistant Add-on
 * %%
 * Copyright (C) 2023 - 2026 Flowing Code
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.flowingcode.vaadin.addons.chatassistant;

import com.flowingcode.vaadin.addons.demo.DemoSource;
import com.flowingcode.vaadin.addons.demo.SourcePosition;
import com.google.common.base.Strings;
import com.vaadin.flow.component.DetachEvent;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.CssImport;
import com.vaadin.flow.component.icon.SvgIcon;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.data.renderer.ComponentRenderer;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import java.time.LocalDateTime;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;

@DemoSource(sourcePosition = SourcePosition.PRIMARY)
@PageTitle("Generative Answer Demo")
@Route(value = "chat-assistant/generative-demo", layout = ChatAssistantDemoView.class)
@CssImport("./styles/chat-assistant-styles-demo.css")
public class ChatAssistantGenerativeDemo extends VerticalLayout {

  // Dedicated daemon executor for the streaming task, so its blocking sleeps never tie up the shared
  // ForkJoinPool.commonPool(); shut down when the view detaches.
  private final ExecutorService executor =
      Executors.newSingleThreadExecutor(
          r -> {
            Thread t = new Thread(r, "chat-assistant-generative-demo");
            t.setDaemon(true);
            return t;
          });

  public ChatAssistantGenerativeDemo() {
    String sampleText =
        "Hi, I'm an advanced language model. I'm here to help you demonstrate"
            + " how a text-streaming chat component works in Vaadin. As you can see, each word appears"
            + " with a slight pause, simulating the time it would take me to \"think\" and generate"
            + " the next word. I hope this is useful for your demonstration!";

    // Create the assistant with all defaults and give it a custom FAB icon.
    ChatAssistant<CustomMessage> chatAssistant = new ChatAssistant<>();
    SvgIcon icon = new SvgIcon("chatbot.svg");
    icon.setColor("var(--lumo-primary-contrast-color)");
    chatAssistant.setFabIcon(icon);
    chatAssistant.setWindowWidth("400px");
    chatAssistant.setWindowHeight("400px");

    // Render each message with a custom component that also shows its tagline.
    chatAssistant.setMessagesRenderer(
        new ComponentRenderer<CustomChatMessage, CustomMessage>(
            CustomChatMessage::new,
            (component, message) -> {
              ((CustomChatMessage) component).setMessage(message);
              return component;
            }));

    // Echo messages submitted by the user from the chat input.
    chatAssistant.setSubmitListener(
        se ->
            chatAssistant.sendMessage(
                CustomMessage.builder()
                    .messageTime(LocalDateTime.now())
                    .name("User")
                    .content(se.getValue())
                    .tagline("Generated by user")
                    .build()));

    // Text area pre-filled with the answer that will be streamed.
    TextArea message = new TextArea();
    message.setLabel("Enter a message from the assistant");
    message.setSizeFull();
    message.setValue(sampleText);
    message.addKeyPressListener(
        ev -> {
          if (Strings.isNullOrEmpty(chatAssistant.getWhoIsTyping())) {
            chatAssistant.setWhoIsTyping("Assistant is generating an answer ...");
          }
        });
    message.addBlurListener(ev -> chatAssistant.clearWhoIsTyping());

    // Send the composed text as a single assistant message.
    Button chat = new Button("Chat");
    chat.addClickListener(
        ev -> {
          chatAssistant.sendMessage(
              CustomMessage.builder()
                  .content(message.getValue())
                  .messageTime(LocalDateTime.now())
                  .name("Assistant")
                  .avatar("chatbot.png")
                  .tagline("Generated by assistant")
                  .build());
          message.clear();
        });

    // Send an empty loading message and stream the answer into it word by word.
    Button chatWithThinking = new Button("Chat With Generative Thinking");
    chatWithThinking.addClickListener(
        ev -> {
          String answer = message.getValue();
          CustomMessage delayedMessage =
              CustomMessage.builder()
                  .loading(true)
                  .content("")
                  .messageTime(LocalDateTime.now())
                  .name("Assistant")
                  .avatar("chatbot.png")
                  .tagline("Generated by assistant")
                  .build();
          chatAssistant.sendMessage(delayedMessage);

          UI currentUI = UI.getCurrent();
          CompletableFuture.runAsync(
              () -> {
                try {
                  TimeUnit.MILLISECONDS.sleep(500);
                  currentUI.access(() -> delayedMessage.setLoading(false));
                  // Emit the answer word by word. Thread.sleep propagates InterruptedException on
                  // executor.shutdownNow(), aborting the loop so no further ui.access runs on a
                  // detached view.
                  for (String word : answer.split("\\s+")) {
                    Thread.sleep(ThreadLocalRandom.current().nextLong(50, 250));
                    String chunk = word + " ";
                    currentUI.access(
                        () -> {
                          delayedMessage.setContent(delayedMessage.getContent() + chunk);
                          chatAssistant.updateMessage(delayedMessage);
                        });
                  }
                } catch (InterruptedException e) {
                  Thread.currentThread().interrupt();
                }
              },
              executor);
          message.clear();
        });

    // Seed the conversation with a greeting and open the window.
    chatAssistant.sendMessage(
        CustomMessage.builder()
            .content("Hello, I am here to assist you")
            .messageTime(LocalDateTime.now())
            .name("Assistant")
            .avatar("chatbot.png")
            .tagline("Generated by assistant")
            .build());
    chatAssistant.setOpened(true);

    HorizontalLayout row = new HorizontalLayout(chat, chatWithThinking);
    row.getStyle().set("flex-wrap", "wrap");

    add(message, row, chatAssistant);
  }

  @Override
  protected void onDetach(DetachEvent detachEvent) {
    executor.shutdownNow();
    super.onDetach(detachEvent);
  }
}
