/*-
 * #%L
 * Chat Assistant Add-on
 * %%
 * Copyright (C) 2023 - 2026 Flowing Code
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package com.flowingcode.vaadin.addons.chatassistant;

import com.flowingcode.vaadin.addons.demo.DemoSource;
import com.flowingcode.vaadin.addons.demo.SourcePosition;
import com.google.common.base.Strings;
import com.vaadin.flow.component.DetachEvent;
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.dependency.CssImport;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.data.renderer.ComponentRenderer;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import java.time.LocalDateTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

@DemoSource(sourcePosition = SourcePosition.PRIMARY)
@PageTitle("Basic Demo")
@Route(value = "chat-assistant/basic-demo", layout = ChatAssistantDemoView.class)
@CssImport("./styles/chat-assistant-styles-demo.css")
public class ChatAssistantDemo extends VerticalLayout {

  // Daemon-threaded scheduler for the delayed "thinking" reply, so it never blocks JVM shutdown; it is
  // shut down when the view detaches.
  private final ScheduledExecutorService scheduler =
      Executors.newSingleThreadScheduledExecutor(
          r -> {
            Thread t = new Thread(r, "chat-assistant-demo-scheduler");
            t.setDaemon(true);
            return t;
          });

  public ChatAssistantDemo() {
    // Create the assistant with all defaults
    ChatAssistant<CustomMessage> chatAssistant = new ChatAssistant<>();
    // Set a sensible default window size
    chatAssistant.setWindowWidth("400px");
    chatAssistant.setWindowHeight("400px");

    // Render each message with a custom component that also shows its tagline.
    chatAssistant.setMessagesRenderer(
        new ComponentRenderer<CustomChatMessage, CustomMessage>(
            CustomChatMessage::new,
            (component, message) -> {
              ((CustomChatMessage) component).setMessage(message);
              return component;
            }));

    // Echo messages submitted by the user from the chat input.
    chatAssistant.setSubmitListener(
        se ->
            chatAssistant.sendMessage(
                CustomMessage.builder()
                    .messageTime(LocalDateTime.now())
                    .name("User")
                    .content(se.getValue())
                    .tagline("Generated by user")
                    .build()));

    // Text area used to compose the assistant's answer.
    TextArea message = new TextArea();
    message.setLabel("Enter a message from the assistant");
    message.setSizeFull();
    message.addKeyPressListener(
        ev -> {
          if (Strings.isNullOrEmpty(chatAssistant.getWhoIsTyping())) {
            chatAssistant.setWhoIsTyping("Assistant is generating an answer ...");
          }
        });
    message.addBlurListener(ev -> chatAssistant.clearWhoIsTyping());

    // Send the composed text as an assistant message.
    Button chat = new Button("Chat");
    chat.addClickListener(
        ev -> {
          chatAssistant.sendMessage(
              CustomMessage.builder()
                  .content(message.getValue())
                  .messageTime(LocalDateTime.now())
                  .name("Assistant")
                  .avatar("chatbot.png")
                  .tagline("Generated by assistant")
                  .build());
          message.clear();
        });

    // Send a message in a loading state, then resolve it after 5 seconds.
    Button chatWithThinking = new Button("Chat With Thinking");
    chatWithThinking.addClickListener(
        ev -> {
          CustomMessage delayedMessage =
              CustomMessage.builder()
                  .loading(true)
                  .content(message.getValue())
                  .messageTime(LocalDateTime.now())
                  .name("Assistant")
                  .avatar("chatbot.png")
                  .tagline("Generated by assistant")
                  .build();
          chatAssistant.sendMessage(delayedMessage);

          UI currentUI = UI.getCurrent();
          scheduler.schedule(
              () ->
                  currentUI.access(
                      () -> {
                        delayedMessage.setLoading(false);
                        chatAssistant.updateMessage(delayedMessage);
                      }),
              5,
              TimeUnit.SECONDS);
          message.clear();
        });

    Button unread = new Button("Toggle unread badge");
    unread.addClickListener(
        ev -> {
          if (chatAssistant.getUnreadMessages() > 0) {
            chatAssistant.setUnreadMessages(0);
          } else {
            chatAssistant.setUnreadMessages((int) (Math.random() * 98) + 1);
          }
        });

    // Seed the conversation
    chatAssistant.sendMessage(
        CustomMessage.builder()
            .content("Hello, I am here to assist you")
            .messageTime(LocalDateTime.now())
            .name("Assistant")
            .avatar("chatbot.png")
            .tagline("Generated by assistant")
            .build());

    HorizontalLayout row = new HorizontalLayout(chat, chatWithThinking, unread);
    row.setSpacing(true);
    row.setPadding(false);
    row.getStyle().set("flex-wrap", "wrap");

    unread.click();
    chatAssistant.setOpened(true);

    add(message, row, chatAssistant);
  }

  @Override
  protected void onDetach(DetachEvent detachEvent) {
    scheduler.shutdownNow();
    super.onDetach(detachEvent);
  }
}
